NhatMinh/Ecommerce/Models/SanPham.cs
namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SanPham")]
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            BinhLuan = new HashSet<BinhLuan>();
            ChiTietDonHang = new HashSet<ChiTietDonHang>();
            ChiTietPhieuNhap = new HashSet<ChiTietPhieuNhap>();
            ChiTietSP = new HashSet<ChiTietSP>();
        }

        [Key]
        [Display(Name = "Mã Sản Phẩm")]
        public int MaSanPham { get; set; }

        [Required]
        [StringLength(200)]
        [Display(Name = "Tên Sản Phẩm")]
        public string TenSanPham { get; set; }

        [StringLength(100)]
        [Display(Name = "Ảnh Bìa")]
        public string AnhBia { get; set; }

        [StringLength(255)]
        [Display(Name = "Màn Hình")]
        public string ManHinh { get; set; }

        [StringLength(255)]
        [Display(Name = "CPU")]
        public string CPU { get; set; }

        [StringLength(255)]
        [Display(Name = "Camera Trước")]
        public string Camera_Truoc { get; set; }

        [StringLength(255)]
        [Display(Name = "Camera Sau")]
        public string Camera_Sau { get; set; }

        [StringLength(200)]
        [Display(Name = "Hệ Điều Hành")]
        public string HeDieuHanh { get; set; }

        [StringLength(255)]
        [Display(Name = "Quay Phim")]
        public string QuayPhim { get; set; }

        [StringLength(200)]
        [Display(Name = "Pin")]
        public string Pin { get; set; }

        [Display(Name = "Thời Gian Bảo Hành")]
        public int? ThoiGianBaoHanh { get; set; }

        [Display(Name = "Thông Tin Sản Phẩm")]
        public string ThongTinThemVeSP { get; set; }

        [Display(Name = "Trạng Thái")]
        public int? TrangThai { get; set; }

        [Display(Name = "Mã Loại Sản Phẩm")]
        public int? MaLoaiSP { get; set; }

        [Display(Name = "Mã Hãng Sản Xuất")]
        public int? MaHangSX { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuan { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhap { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietSP> ChiTietSP { get; set; }

        [Display(Name = "Hãng Sản Xuất")]
        public virtual HangSanXuat HangSanXuat { get; set; }

        [Display(Name = "Hình Ảnh")]
        public virtual HinhAnh HinhAnh { get; set; }

        [Display(Name = "Loại Sản Phẩm")]
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}

NhatMinh/Ecommerce/Areas/Admin/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ecommerce.Models;

namespace Ecommerce.Areas.Admin.Controllers
{
    public class SanPhamsController : Controller
    {
        private DBEcommerce db = new DBEcommerce();

        // GET: Admin/SanPhams
        public ActionResult Index()
        {
            var sanPham = db.SanPham.Include(s => s.HangSanXuat).Include(s => s.HinhAnh).Include(s => s.LoaiSanPham);
            return View(sanPham.ToList());
        }

        // GET: Admin/SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPham.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }

            return View(sanPham);
        }

        // GET: Admin/SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaHangSX = new SelectList(db.HangSanXuat, "MaHangSX", "TenHangSX");
            ViewBag.MaSanPham = new SelectList(db.HinhAnh, "MaSanPham", "HinhAnh1");
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPham, "MaLoaiSP", "TenLoaiSP");
            ViewBag.MauSac = db.MauSac.ToList();

            return View();
        }

        // POST: Admin/SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSanPham,TenSanPham,AnhBia,ManHinh,CPU,Camera_Truoc,Camera_Sau,HeDieuHanh,QuayPhim,Pin,ThoiGianBaoHanh,ThongTinThemVeSP,TrangThai,MaLoaiSP,MaHangSX")] SanPham sanPham, HttpPostedFileBase AnhBiaFile)
        {
            if (ModelState.IsValid)
            {
                if (AnhBiaFile != null && AnhBiaFile.ContentLength > 0)
                {
                    // Lấy tên tệp và đường dẫn lưu trữ
                    var fileName = Path.GetFileName(AnhBiaFile.FileName);
                    var path = Path.Combine(Server.MapPath("~/Assets/Customers/img/HinhAnhSanPham/"), fileName);

                    // Lưu tệp vào đường dẫn
                    AnhBiaFile.SaveAs(path);

                    // Cập nhật thuộc tính AnhBia với đường dẫn tệp
                    sanPham.AnhBia = fileName;
                }

                db.SanPham.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.MaHangSX = new SelectList(db.HangSanXuat, "MaHangSX", "TenHangSX", sanPham.MaHangSX);
            ViewBag.MaSanPham = new SelectList(db.HinhAnh, "MaSanPham", "HinhAnh1", sanPham.MaSanPham);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPham, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);
            return View(sanPham);
        }

        // GET: Admin/SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPham.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaHangSX = new SelectList(db.HangSanXuat, "MaHangSX", "TenHangSX", sanPham.MaHangSX);
            ViewBag.MaSanPham = new SelectList(db.HinhAnh, "MaSanPham", "HinhAnh1", sanPham.MaSanPham);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPham, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);


            // Hiển thị chi tiết sản phẩm
            var chiTietSanPham = db.ChiTietSP.Where(n => n.MaSanPham == sanPham.MaSanPham).OrderBy(n=>n.MauSac.TenMauSac).ToList();
            ViewBag.ChiTietSanPham = chiTietSanPham;

            return View(sanPham);
        }

        // POST: Admin/SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSanPham,TenSanPham,AnhBia,ManHinh,CPU,Camera_Truoc,Camera_Sau,HeDieuHanh,QuayPhim,Pin,ThoiGianBaoHanh,ThongTinThemVeSP,TrangThai,MaLoaiSP,MaHangSX")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaHangSX = new SelectList(db.HangSanXuat, "MaHangSX", "TenHangSX", sanPham.MaHangSX);
            ViewBag.MaSanPham = new SelectList(db.HinhAnh, "MaSanPham", "HinhAnh1", sanPham.MaSanPham);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPham, "MaLoaiSP", "TenLoaiSP", sanPham.MaLoaiSP);
            return View(sanPham);
        }

        // GET: Admin/SanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPham.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: Admin/SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPham.Find(id);
            db.SanPham.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

NhatMinh/Ecommerce/Areas/Admin/Views/SanPhams/Create.cshtml
@using Ecommerce.Models
@model SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    IEnumerable<MauSac> lstMauSac = ViewBag.MauSac as IEnumerable<MauSac>;
}

<div class="title-block">
    <h1 class="title"> Thêm Mới Sản Phẩm </h1>
</div>

@using (Html.BeginForm("Create", "SanPhams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="AnhBiaFile" required />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManHinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ManHinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ManHinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPU, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPU, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPU, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Camera_Truoc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Camera_Truoc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Camera_Truoc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Camera_Sau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Camera_Sau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Camera_Sau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HeDieuHanh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HeDieuHanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HeDieuHanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuayPhim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuayPhim, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuayPhim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThoiGianBaoHanh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThoiGianBaoHanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThoiGianBaoHanh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThongTinThemVeSP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThongTinThemVeSP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThongTinThemVeSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoaiSP, "MaLoaiSP", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoaiSP", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoaiSP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaHangSX, "MaHangSX", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaHangSX", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaHangSX, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Màu Sắc</label>
            <div class="col-md-10">
                <select name="MaMauSac" class="form-control">
                    @foreach (var item in lstMauSac)
                    {
                        <option value="@item.MaMauSac">@item.TenMauSac</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary-outline">Thêm Mới</button>  <a href="~/Admin/Home/Index" class="btn btn-danger-outline">Trở Về</a>
            </div>
        </div>
    </div>
}

NhatMinh/Ecommerce/Areas/Admin/Views/SanPhams/Delete.cshtml
@model Ecommerce.Models.SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="title-block">
    <h1 class="title"> Xóa Sản Phẩm </h1>
</div>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HangSanXuat.TenHangSX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HangSanXuat.TenHangSX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh.HinhAnh1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh.HinhAnh1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiSanPham.TenLoaiSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoaiSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSanPham)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhBia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhBia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ManHinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManHinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CPU)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CPU)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Camera_Truoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Camera_Truoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Camera_Sau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Camera_Sau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HeDieuHanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HeDieuHanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuayPhim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuayPhim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThoiGianBaoHanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThoiGianBaoHanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThongTinThemVeSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThongTinThemVeSP)
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary-outline">Xóa</button>  <a href="~/Admin/Home/Index" class="btn btn-danger-outline">Trở Về</a>
            </div>
        </div>
    }
</div>

NhatMinh/Ecommerce/Areas/Admin/Views/SanPhams/Details.cshtml
@using Ecommerce.Models
@model SanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="title-block">
    <h1 class="title"> Chi Tiết Sản Phẩm </h1>
</div>
<div>
    <dl class="dl-horizontal">
        <dt>
            Tên Hãng Sản Xuất
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HangSanXuat.TenHangSX)
        </dd>

        <dt>
            Hình Ảnh
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh.HinhAnh1)
        </dd>

        <dt>
            Tên Loại Sản Phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoaiSP)
        </dd>

        <dt>
            Tên Sản Phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSanPham)
        </dd>

        <dt>
            Ảnh Bìa
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhBia)
        </dd>

        <dt>
            Màn Hình
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ManHinh)
        </dd>

        <dt>
            CPU
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CPU)
        </dd>

        <dt>
            Camera Trước
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Camera_Truoc)
        </dd>

        <dt>
            Camera Sau
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Camera_Sau)
        </dd>

        <dt>
           Hệ Điều Hành
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HeDieuHanh)
        </dd>

        <dt>
            Quay Phim
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuayPhim)
        </dd>

        <dt>
            Pin
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pin)
        </dd>

        <dt>
            Thời Gian Bảo Hành
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThoiGianBaoHanh)
        </dd>

        <dt>
            Thông Tin Thêm Về Sản Phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThongTinThemVeSP)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Cập Nhật", "Edit", new { id = Model.MaSanPham }) 
</p>

NhatMinh/Ecommerce/Areas/Admin/Views/SanPhams/Index.cshtml
@model IEnumerable<Ecommerce.Models.SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.HangSanXuat.TenHangSX)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HinhAnh.HinhAnh1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LoaiSanPham.TenLoaiSP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TenSanPham)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AnhBia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ManHinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CPU)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Camera_Truoc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Camera_Sau)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HeDieuHanh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QuayPhim)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThoiGianBaoHanh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThongTinThemVeSP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TrangThai)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.HangSanXuat.TenHangSX)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HinhAnh.HinhAnh1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LoaiSanPham.TenLoaiSP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenSanPham)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AnhBia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ManHinh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CPU)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Camera_Truoc)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Camera_Sau)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HeDieuHanh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QuayPhim)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ThoiGianBaoHanh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ThongTinThemVeSP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TrangThai)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MaSanPham }) |
            @Html.ActionLink("Details", "Details", new { id=item.MaSanPham }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MaSanPham })
        </td>
    </tr>
}

</table>