NhatMinh/Ecommerce/Areas/Admin/Controllers/ThongKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Ecommerce.Models;

namespace Ecommerce.Areas.Admin.Controllers
{
    public class ThongKeController : Controller
    {
        DBEcommerce db = new DBEcommerce();
        public ActionResult Thongke()
        {
            //ViewBag.DoanhThuNgayHomNay = DoanhThuNgayHomNay();
            ViewBag.DoanhThuTong = DoanhThuTong();
            ViewBag.DoanhThuXacNhan = DoanhThuXacNhan();
            ViewBag.DoanhThuDangGiao = DoanhThuDangGiao();
            ViewBag.DoanhThuDaGiao = DoanhThuDaGiao();
            ViewBag.DoanhThuDaHuy = DoanhThuDaHuy();
            ViewBag.CountDonHang = CountDonHang();
            ViewBag.CountDonHangXacNhan = CountDonHangXacNhan();
            ViewBag.CountDonHangDangGiao = CountDonHangDangGiao();
            ViewBag.CountDonHangDaGiao = CountDonHangDaGiao();
            ViewBag.CountDonHangDaHuy = CountDonHangDaHuy();
            ViewBag.CountNhanVien = CountNhanVien();
            ViewBag.CountKhachHang = CountKhachHang();
            return View();
        }
        #region Tính Toán

        // Doanh thu tổng (Tổng thành tiền trong Bảng CTSP)
        public decimal DoanhThuTong()
        {
            decimal doanhthutong = db.ChiTietDonHang.Sum(n => n.ThanhTien).Value;
            return doanhthutong;
        }
        public decimal DoanhThuXacNhan()
        {
            try
            {
                decimal doanhthuxacnhan = (decimal)(from ctdh in db.ChiTietDonHang
                                                    join dh in db.DonHang
                                                    on ctdh.MaDonHang equals dh.MaDonHang
                                                    where dh.TrangThai == 0
                                                    group ctdh by dh.TrangThai into g
                                                    select g.Sum(n => n.ThanhTien)).FirstOrDefault();
                return doanhthuxacnhan;
            }
            catch (System.Exception)
            {
                return 0;
            }
        }
        public decimal DoanhThuDangGiao()
        {
            try
            {
                decimal doanhthuxacnhan = (decimal)(from ctdh in db.ChiTietDonHang
                                                    join dh in db.DonHang
                                                    on ctdh.MaDonHang equals dh.MaDonHang
                                                    where dh.TrangThai == 1
                                                    group ctdh by dh.TrangThai into g
                                                    select g.Sum(n => n.ThanhTien)).FirstOrDefault();
                return doanhthuxacnhan;
            }
            catch (System.Exception)
            {
                return 0;
            }
        }
        public decimal DoanhThuDaGiao()
        {
            try
            {
                decimal doanhthuxacnhan = (decimal)(from ctdh in db.ChiTietDonHang
                                                    join dh in db.DonHang
                                                    on ctdh.MaDonHang equals dh.MaDonHang
                                                    where dh.TrangThai == 2
                                                    group ctdh by dh.TrangThai into g
                                                    select g.Sum(n => n.ThanhTien)).FirstOrDefault();
                return doanhthuxacnhan;
            }
            catch (System.Exception)
            {
                return 0;
            }
        }
        public decimal DoanhThuDaHuy()
        {
            try
            {
                decimal doanhthuxacnhan = (decimal)(from ctdh in db.ChiTietDonHang
                                                    join dh in db.DonHang
                                                    on ctdh.MaDonHang equals dh.MaDonHang
                                                    where dh.TrangThai == 3
                                                    group ctdh by dh.TrangThai into g
                                                    select g.Sum(n => n.ThanhTien)).FirstOrDefault();
                return doanhthuxacnhan;
            }
            catch (System.Exception)
            {
                return 0;
            }
        }
        public decimal DoanhThuNgayHomNay()
        {
            //try
            //{
            string dt = "2021/08/22";
            //string dt = DateTime.Now.ToString("dd/MM/yyyy");
            decimal doanhthuHomNay = (decimal)(from ctdh in db.ChiTietDonHang
                                               join dh in db.DonHang
                                               on ctdh.MaDonHang equals dh.MaDonHang
                                               where dh.NgayDat == DateTime.Parse(dt)
                                               group ctdh by dh.TrangThai into g
                                               select g.Sum(n => n.ThanhTien)).FirstOrDefault();
            return doanhthuHomNay;
            //}
            //catch (System.Exception)
            //{
            //    return 0;
            //}
        }
        #endregion
        #region Dếm Số Lượng
        public int CountDonHang()
        {
            int countdh = db.DonHang.Count();
            return countdh;
        }
        public int CountDonHangXacNhan()
        {
            int countdh = db.DonHang.Count(n => n.TrangThai == 0);
            return countdh;
        }
        public int CountDonHangDangGiao()
        {
            int countdh = db.DonHang.Count(n => n.TrangThai == 1);
            return countdh;
        }
        public int CountDonHangDaGiao()
        {
            int countdh = db.DonHang.Count(n => n.TrangThai == 2);
            return countdh;
        }
        public int CountDonHangDaHuy()
        {
            int countdh = db.DonHang.Count(n => n.TrangThai == 3);
            return countdh;
        }
        // Số lượng nhân viên và khách hàng
        public int CountNhanVien()
        {
            int countnv = db.NhanVien.Count();
            return countnv;
        }
        public int CountKhachHang()
        {
            int countnv = db.NhanVien.Count();
            return countnv;
        }
        #endregion
        #region Thống kê hôm nay
        // Sản Phẩm bán đượcs
        public ActionResult SanPhamBanDuoc()
        {
            string dt = DateTime.Now.ToString("dd/MM/yyyy");
            DateTime datenow = DateTime.Now.Date;
            var dh = db.DonHang.Where(n => n.NgayDat == DateTime.Now).ToList();
            return View(dh);
        }
        // Thống kê tháng năm
        public ActionResult TKThangNam(FormCollection f)
        {
            int ngay = int.Parse(f["ngay"]);
            int thang = int.Parse(f["thang"]);
            int nam = int.Parse(f["nam"]);
            List<DonHang> dh;

            if (ngay == 32)
            {
                dh = db.DonHang.Where(n => n.NgayDat.Month == thang && n.NgayDat.Year == nam).ToList();
            }
            else
            {
                dh = db.DonHang.Where(n => n.NgayDat.Day == ngay && n.NgayDat.Month == thang && n.NgayDat.Year == nam).ToList();
            }

            decimal tongtien = 0;
            foreach (var item in dh)
            {
                tongtien += decimal.Parse(item.ChiTietDonHang.Sum(n => n.ThanhTien).Value.ToString());
            }
            ViewBag.thang = thang;
            ViewBag.nam = nam;
            ViewBag.tt = tongtien;
            #region Doanh thu cũ
            ViewBag.DoanhThuTong = DoanhThuTong();
            ViewBag.DoanhThuXacNhan = DoanhThuXacNhan();
            ViewBag.DoanhThuDangGiao = DoanhThuDangGiao();
            ViewBag.DoanhThuDaGiao = DoanhThuDaGiao();
            ViewBag.DoanhThuDaHuy = DoanhThuDaHuy();
            ViewBag.CountDonHang = CountDonHang();
            ViewBag.CountDonHangXacNhan = CountDonHangXacNhan();
            ViewBag.CountDonHangDangGiao = CountDonHangDangGiao();
            ViewBag.CountDonHangDaGiao = CountDonHangDaGiao();
            ViewBag.CountDonHangDaHuy = CountDonHangDaHuy();
            ViewBag.CountNhanVien = CountNhanVien();
            ViewBag.CountKhachHang = CountKhachHang();
            #endregion
            return View();
        }
        #endregion
    }

}

NhatMinh/Ecommerce/Areas/Admin/Views/ThongKe/SanPhamBanDuoc.cshtml
@using Ecommerce.Models
@model List<DonHang>
@{
    ViewBag.Title = "SanPhamBanDuoc";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>San Pham Ban Duoc Hom Nay</h2>
@foreach (var item in Model)
{
    @item.MaDonHang
    <br />
    @item.NgayDat
}

NhatMinh/Ecommerce/Areas/Admin/Views/ThongKe/TKThangNam.cshtml
@{
    ViewBag.Title = "Thống kê Tháng Năm";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="title-block">
    <h1 class="title"> Thống Kê </h1>
</div>
<section class="section">
    <div class="row sameheight-container">
        <div class="col-md-6">
            <div class="card card-block sameheight-item" style="height: 119px;">
                <div class="title-block">
                    <h3 class="title"> Theo Tháng </h3>
                </div>
                @using (Html.BeginForm("TKThangNam", "ThongKe"))
                {
                    <div class="form-inline">
                        <div class="form-group">
                            <label for="exampleInputEmail3">Chọn Ngày &nbsp; </label>
                            <select name="ngay">
                                <option selected value="32"></option>
                                @for (int i = 1; i <= 31; i++)
                                {
                                    <option value="@i">@i</option>
                                }
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail3">Chọn tháng &nbsp; </label>
                            <select name="thang">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                                <option value="11">11</option>
                                <option value="12">12</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputPassword3">&nbsp;&nbsp;&nbsp;&nbsp; Chọn năm &nbsp; </label>
                            <select name="nam">
                                <option value="2016">2016</option>
                                <option value="2017">2017</option>
                                <option value="2018">2018</option>
                                <option value="2019">2019</option>
                                <option value="2020">2020</option>
                                <option value="2021">2021</option>
                                <option value="2022">2022</option>
                                <option value="2023">2023</option>
                                <option selected value="2024">2024</option>
                            </select>
                        </div>
                        &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;
                        <button type="submit" class="btn btn-primary">Thực Hiện</button>
                    </div>
                }
            </div>
        </div>
        <!-- #region kết quả -->
        @if (ViewBag.thang != null)
        {
            <div class="col-md-6">
                <div class="card card-block sameheight-item" style="height: 119px;">
                    <div class="title-block">
                        <h3 class="title"> Thống kê tháng @ViewBag.thang/@ViewBag.Nam là </h3>
                    </div>
                    <div class="form-inline">
                        <div class="form-group">
                            <label for="exampleInputEmail3">
                                Tổng tiền: @String.Format("{0:N0} VND", ViewBag.tt) vnđ &nbsp;

                            </label>
                        </div>
                    </div>
                </div>
            </div>
        }
        <!-- #endregion -->
    </div>
</section>
<!-- #region Kết quả -->
<!-- #endregion -->
<section class="section" style="display:none">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-block">
                    <div class="card-title-block">
                        <h3 class="title"> Hiện Tại </h3>
                    </div>
                    <section class="example">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Phân Loại</th>
                                    <th>Số Đơn</th>
                                    <th>Tổng Tiền</th>
                                    <th>Chi Tiết</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Hôm Nay</td>
                                    <td>@ViewBag.DoanhThuNgayHomNay vnđ</td>

                                </tr>
                                <tr>
                                    <td>Tháng Nay</td>
                                    <td>@ViewBag.CountDonHangDangGiao</td>
                                    <td>
                                        @String.Format("{0:N0} VND", ViewBag.DoanhThuDangGiao) vnđ
                                    </td>
                                    <td><a href="~/Admin/DonHang/DonHangDangGiao"><i class="fa fa-info-circle" aria-hidden="true"></i> Chi Tiết</a></td>
                                </tr>
                                <tr>
                                    <td>Năm Nay</td>
                                    <td><b style="color:red">@ViewBag.CountDonHangDaGiao</b></td>
                                    <td><b style="color:red">@String.Format("{0:0,0}", ViewBag.DoanhThuDaGiao) </b>vnđ</td>
                                    <td><a href="~/Admin/DonHang/DonHangDaGiao"><i class="fa fa-info-circle" aria-hidden="true"></i> Chi Tiết</a></td>
                                </tr>
                                <tr>
                                    <td>SUM</td>
                                    <th>@ViewBag.CountDonHang</th>
                                    <th>@String.Format("{0:0,0}", ViewBag.DoanhThuTong) vnđ</th>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-block">
                    <div class="card-title-block">
                        <h3 class="title"> Thành viên </h3>
                    </div>
                    <section class="example">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Phân Loại</th>
                                    <th>Thành Viên</th>
                                    <th>Chi Tiết</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Nhân Viên</td>
                                    <td>@ViewBag.CountNhanVien</td>
                                    <td><a href="~/Admin/NhanVien/Index"><i class="fa fa-info-circle" aria-hidden="true"></i> Chi Tiết</a></td>

                                </tr>
                                <tr>
                                    <td>Khách Hàng</td>
                                    <td>@ViewBag.CountKhachHang</td>
                                    <td><a href="~/Admin/KhachHang/Index"><i class="fa fa-info-circle" aria-hidden="true"></i> Chi Tiết</a></td>

                                </tr>
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-block">
                    <div class="card-title-block">
                        <h3 class="title"> Đơn Hàng </h3>
                    </div>
                    <section class="example">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Phân Loại</th>
                                    <th>Số Đơn</th>
                                    <th>Tổng Tiền</th>
                                    <th>Chi Tiết</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Xử Lý</td>
                                    <td>@ViewBag.CountDonHangXacNhan</td>
                                    <td>@String.Format("{0:0,0}", ViewBag.DoanhThuXacNhan) vnđ</td>
                                    <td><a href="~/Admin/DonHang/DonHangXacNhan"><i class="fa fa-info-circle" aria-hidden="true"></i> Chi Tiết</a></td>

                                </tr>
                                <tr>
                                    <td>Đang Giao</td>
                                    <td>@ViewBag.CountDonHangDangGiao</td>
                                    <td>@String.Format("{0:0,0}", ViewBag.DoanhThuDangGiao) vnđ</td>
                                    <td><a href="~/Admin/DonHang/DonHangDangGiao"><i class="fa fa-info-circle" aria-hidden="true"></i> Chi Tiết</a></td>
                                </tr>
                                <tr>
                                    <td>Đã giao</td>
                                    <td><b style="color:red">@ViewBag.CountDonHangDaGiao</b></td>
                                    <td><b style="color:red">@String.Format("{0:0,0}", ViewBag.DoanhThuDaGiao) </b>vnđ</td>
                                    <td><a href="~/Admin/DonHang/DonHangDaGiao"><i class="fa fa-info-circle" aria-hidden="true"></i> Chi Tiết</a></td>
                                </tr>
                                <tr>
                                    <td>Đã Hủy</td>
                                    <td>@ViewBag.CountDonHangDaHuy</td>
                                    <td>@String.Format("{0:0,0}", ViewBag.DoanhThuDaHuy) vnđ</td>
                                    <td><a href="~/Admin/DonHang/DonHangDaHuy"><i class="fa fa-info-circle" aria-hidden="true"></i> Chi Tiết</a></td>
                                </tr>
                                <tr>
                                    <td>SUM</td>
                                    <th>@ViewBag.CountDonHang</th>
                                    <th>@String.Format("{0:0,0}", ViewBag.DoanhThuTong) vnđ</th>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-block">
                    <div class="card-title-block">
                        <h3 class="title"> Thành viên </h3>
                    </div>
                    <section class="example">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Phân Loại</th>
                                    <th>Thành Viên</th>
                                    <th>Chi Tiết</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Nhân Viên</td>
                                    <td>@ViewBag.CountNhanVien</td>
                                    <td><a href="~/Admin/NhanVien/Index"><i class="fa fa-info-circle" aria-hidden="true"></i> Chi Tiết</a></td>

                                </tr>
                                <tr>
                                    <td>Khách Hàng</td>
                                    <td>@ViewBag.CountKhachHang</td>
                                    <td><a href="~/Admin/KhachHang/Index"><i class="fa fa-info-circle" aria-hidden="true"></i> Chi Tiết</a></td>

                                </tr>
                            </tbody>
                        </table>
                    </section>
                </div>
            </div>
        </div>
    </div>
</section>